server:
  port: 8001

spring:
  application:
    name: dept-provider

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: dept-provider-8001
    prefer-ip-address: true     #访问路径可以显示IP地址
info:
  app.name: onion
  app.version: 1.0.0
  app.author: alex
  app.since: 2019-02-16
